name: Docker Image CI

on:
  pull_request: #can be changed to pull_request_review to build image after approval
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - 'terraform/**'    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd flaskliveapi
        docker build . --file Dockerfile --tag shrey03/flaskapilive:$(date +%s)

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: shrey03/flaskapilive:$(date +%s)
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
